Reproduce a bug where there is a compiler warning where I don't think it should
$ mix compile
Compiling 2 files (.ex)
warning: incompatible types:

    map() !~ %{optional(dynamic()) => dynamic()} | %{optional(dynamic()) => dynamic()}

in expression:

    # lib/the_bug.ex:8
    conn.assigns

where "conn" was given the type map() | map() in:

    # lib/the_bug.ex:1
    [conn, params] = [conn, params]

where "conn" was given the type map() (due to calling var.field) in:

    # lib/the_bug.ex:8
    conn.assigns

HINT: "var.field" (without parentheses) implies "var" is a map() while "var.fun()" (with parentheses) implies "var" is an atom()

Conflict found at
  lib/the_bug.ex:8: TheBug.PageController.index/2

Generated the_bug app